<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'manage_posts' => [[], ['_controller' => 'App\\Controller\\DashboardController::manage_posts'], [], [['text', '/manage-posts']], [], [], []],
    'manage_users' => [[], ['_controller' => 'App\\Controller\\DashboardController::users'], [], [['text', '/manage-users']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\RestfullController::index'], [], [['text', '/api/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
];
